/* eslint-disable camelcase */
const mappings = {
  BatchSize__c: 'BatchSize',
  CheckFieldLevelSecurity__c: 'IsFieldLevelSecurityEnabled',
  CustomInputClass__c: 'InputParsingClass',
  CustomOutputClass__c: 'OutputParsingClass',
  DeleteOnSuccess__c: 'IsDeletedOnSuccess',
  Description__c: 'Description',
  IgnoreErrors__c: 'IsErrorIgnored',
  InputCustom__c: 'ExpectedInputOtherData',
  InputJson__c: 'ExpectedInputJson',
  InputType__c: 'InputType',
  InputXml__c: 'ExpectedInputXml',
  InterfaceObject__c: 'SourceObject',
  IsDefaultForInterface__c: 'IsSourceObjectDefault',
  IsProcessSuperBulk__c: 'IsProcessSuperBulk',
  Name: 'Name',
  OutputType__c: 'OutputType',
  OverwriteAllNullValues__c: 'IsNullInputsIncludedInOutput',
  PreprocessorClassName__c: 'PreprocessorClassName',
  ProcessNowThreshold__c: 'SynchronousProcessThreshold',
  RequiredPermission__c: 'RequiredPermission',
  RollbackOnError__c: 'IsRollbackOnError',
  SalesforcePlatformCacheType__c: 'ResponseCacheType',
  SampleInputCustom__c: 'PreviewOtherData',
  SampleInputJSON__c: 'PreviewJsonData',
  SampleInputRows__c: 'PreviewSourceObjectData',
  SampleInputXML__c: 'PreviewXmlData',
  TargetOutCustom__c: 'ExpectedOutputOtherData',
  TargetOutDocuSignTemplateId__c: 'TargetOutputDocumentIdentifier',
  TargetOutJson__c: 'ExpectedOutputJson',
  TargetOutPdfDocName__c: 'TargetOutputFileName',
  TargetOutXml__c: 'ExpectedOutputXml',
  TimeToLiveMinutes__c: 'ResponseCacheTtlMinutes',
  Type__c: 'Type',
  UseAssignmentRules__c: 'IsAssignmentRulesUsed',
  XmlOutputSequence__c: 'XmlOutputTagsOrder',
  XmlRemoveDeclaration__c: 'IsXmlDeclarationRemoved',
  GlobalKey__c: 'GlobalKey',
  //   Namespace: 'Namespace',
  //   Version: 'VersionNumber',
};

const mappingsStandard = {
  BatchSize: 'BatchSize',
  IsFieldLevelSecurityEnabled: 'IsFieldLevelSecurityEnabled',
  InputParsingClass: 'InputParsingClass',
  OutputParsingClass: 'OutputParsingClass',
  IsDeletedOnSuccess: 'IsDeletedOnSuccess',
  Description: 'Description',
  IsErrorIgnored: 'IsErrorIgnored',
  ExpectedInputOtherData: 'ExpectedInputOtherData',
  ExpectedInputJson: 'ExpectedInputJson',
  InputType: 'InputType',
  ExpectedInputXml: 'ExpectedInputXml',
  SourceObject: 'SourceObject',
  IsSourceObjectDefault: 'IsSourceObjectDefault',
  IsProcessSuperBulk: 'IsProcessSuperBulk',
  Name: 'Name',
  OutputType: 'OutputType',
  IsNullInputsIncludedInOutput: 'IsNullInputsIncludedInOutput',
  PreprocessorClassName: 'PreprocessorClassName',
  SynchronousProcessThreshold: 'SynchronousProcessThreshold',
  RequiredPermission: 'RequiredPermission',
  IsRollbackOnError: 'IsRollbackOnError',
  ResponseCacheType: 'ResponseCacheType',
  PreviewOtherData: 'PreviewOtherData',
  PreviewJsonData: 'PreviewJsonData',
  PreviewSourceObjectData: 'PreviewSourceObjectData',
  PreviewXmlData: 'PreviewXmlData',
  ExpectedOutputOtherData: 'ExpectedOutputOtherData',
  TargetOutputDocumentIdentifier: 'TargetOutputDocumentIdentifier',
  ExpectedOutputJson: 'ExpectedOutputJson',
  TargetOutputFileName: 'TargetOutputFileName',
  ExpectedOutputXml: 'ExpectedOutputXml',
  ResponseCacheTtlMinutes: 'ResponseCacheTtlMinutes',
  Type: 'Type',
  IsAssignmentRulesUsed: 'IsAssignmentRulesUsed',
  XmlOutputTagsOrder: 'XmlOutputTagsOrder',
  IsXmlDeclarationRemoved: 'IsXmlDeclarationRemoved',
  GlobalKey: 'GlobalKey',
};

export default { mappings, mappingsStandard };
