/* eslint-disable camelcase */
const mappings = {
  AdditionalInformation__c: 'Description',
  CustomJavaScript__c: 'CustomJavaScript',
  DisableMetadataCache__c: 'IsMetadataCacheDisabled',
  ElementTypeToHTMLTemplateList__c: 'ElementTypeComponentMapping',
  IsActive__c: 'IsActive',
  IsLwcEnabled__c: 'IsWebCompEnabled',
  IsProcedure__c: 'IsIntegrationProcedure',
  IsReusable__c: 'IsOmniScriptEmbeddable',
  IsTest__c: 'IsTestProcedure',
  Language__c: 'Language',
  LastPreviewPage__c: 'LastPreviewPage',
  LwcId__c: 'WebComponentKey',
  Name: 'Name',
  OmniProcessType__c: 'OmniProcessType',
  ProcedureKey__c: 'OmniProcessKey',
  ProcedureResponseCacheType__c: 'ResponseCacheType',
  PropertySet__c: 'PropertySetConfig',
  RequiredPermission__c: 'RequiredPermission',
  SubType__c: 'SubType',
  TestHTMLTemplates__c: 'CustomHtmlTemplates',
  Type__c: 'Type',
  Version__c: 'VersionNumber',
};

const mappingsStandard = {
  Description: 'Description',
  CustomJavaScript: 'CustomJavaScript',
  IsMetadataCacheDisabled: 'IsMetadataCacheDisabled',
  ElementTypeComponentMapping: 'ElementTypeComponentMapping',
  IsActive: 'IsActive',
  IsWebCompEnabled: 'IsWebCompEnabled',
  IsIntegrationProcedure: 'IsIntegrationProcedure',
  IsOmniScriptEmbeddable: 'IsOmniScriptEmbeddable',
  IsTestProcedure: 'IsTestProcedure',
  Language: 'Language',
  LastPreviewPage: 'LastPreviewPage',
  WebComponentKey: 'WebComponentKey',
  Name: 'Name',
  OmniProcessType: 'OmniProcessType',
  OmniProcessKey: 'OmniProcessKey',
  ResponseCacheType: 'ResponseCacheType',
  PropertySetConfig: 'PropertySetConfig',
  RequiredPermission: 'RequiredPermission',
  SubType: 'SubType',
  CustomHtmlTemplates: 'CustomHtmlTemplates',
  Type: 'Type',
  VersionNumber: 'VersionNumber',
};

export default { mappings, mappingsStandard };
